spring.application.name=eggland
<<<<<<< Updated upstream
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

=======
spring.datasource.url=jdbc:postgresql://localhost:5432/eggland_db
spring.datasource.username=postgres 
#c'est bon ici c'est le meme nom et meme password dans le docker mais pour l'url alors il devient exactement celui d'en haut là
spring.datasource.password=postgres
>>>>>>> Stashed changes

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=1404